// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using agora.Data;

#nullable disable

namespace agora.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    partial class ForumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("agora.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("mediumtext")
                        .HasColumnName("body");

                    b.HasKey("Id", "UserId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "UserId" }, "fk_comments_user_idx");

                    b.HasIndex(new[] { "Id" }, "id_UNIQUE")
                        .IsUnique();

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("agora.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("mediumtext")
                        .HasColumnName("body");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Likes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("likes")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("tinytext")
                        .HasColumnName("title");

                    b.HasKey("Id", "UserId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "UserId" }, "fk_post_user_idx");

                    b.HasIndex(new[] { "Id" }, "id_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("id_UNIQUE1");

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("agora.PostDraft", b =>
                {
                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.Property<string>("Body")
                        .HasColumnType("mediumtext")
                        .HasColumnName("body");

                    b.Property<string>("Title")
                        .HasColumnType("tinytext")
                        .HasColumnName("title");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "fk_post_draft_user_idx")
                        .IsUnique();

                    b.ToTable("post_draft", (string)null);
                });

            modelBuilder.Entity("agora.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("password");

                    b.Property<int?>("Reputation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reputation")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nickname" }, "nickname_UNIQUE")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("PostComment", b =>
                {
                    b.Property<int>("CommentsId")
                        .HasColumnType("int")
                        .HasColumnName("comments_id");

                    b.Property<uint>("CommentsUserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("comments_user_id");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<uint>("PostUserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("post_user_id");

                    b.HasKey("CommentsId", "CommentsUserId", "PostId", "PostUserId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0, 0 });

                    b.HasIndex(new[] { "PostId", "PostUserId" }, "fk_post_commen_comment_idx");

                    b.HasIndex(new[] { "CommentsId", "CommentsUserId" }, "fk_post_comment_post_idx");

                    b.ToTable("post_comment", (string)null);
                });

            modelBuilder.Entity("agora.Comment", b =>
                {
                    b.HasOne("agora.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_comments_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("agora.Post", b =>
                {
                    b.HasOne("agora.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_post_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("agora.PostDraft", b =>
                {
                    b.HasOne("agora.User", "User")
                        .WithOne("PostDraft")
                        .HasForeignKey("agora.PostDraft", "UserId")
                        .IsRequired()
                        .HasConstraintName("fk_post_draft_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PostComment", b =>
                {
                    b.HasOne("agora.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentsId", "CommentsUserId")
                        .IsRequired()
                        .HasConstraintName("fk_post_comment_comment");

                    b.HasOne("agora.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId", "PostUserId")
                        .IsRequired()
                        .HasConstraintName("fk_post_comment_post");
                });

            modelBuilder.Entity("agora.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostDraft");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
